### ISSUE TITLE
Parallel Temporal Sampler logic question

### ISSUE THREAD

**Issue by zimengzhou1** [amazon-science/tgl#21]
Hi,

I'm not sure if this is the right place to ask, but in the sampler if we perform multi-layer sampling, and the current layer is not the first one, why are we doing binary search in each snapshot to find each root node instead of using the pointer array like in the initial layer?

**Comment by tedzhouhk** [comment]
Hi, thanks for your interest in our work. For multiple layers, the neighbors to sample may not be from the current timestamp. Say at time t, we have n1 at time t1<t as a neighbor for the root node n0. Then, for n1, we want the neighbors to be sampled until time t1 but not the current time t which is pointed by the pointer array. However, this is a design choice in the sampler. Feel free to modify to meet your needs.

**Comment by zimengzhou1** [comment]
Thanks for explaining!
